### ISSUE TITLE
Readme_images

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/Final_Build#2] opened 2017-08-05 22:50 UTC

**Comment by belgiumkansas** [comment] 2017-08-05 22:51
![repo_graph](https://user-images.githubusercontent.com/2038191/28999287-e048f1c8-79f5-11e7-9a24-636e41ebb8e7.jpg)

**Comment by Wofisdk** [comment] 2018-02-03 22:46
Not sure what the issue is. Closing

**Closed by Wofisdk** 2018-02-03 22:46 UTC
